---
title: "Terra - User Growth Per Sector"
author: "Manuel Girbal"
date: "04/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(httr)
library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)
```

## Introduction

....


### Methodology
Data was queried from Flipside Crypto's Velocity database, and the SQL code used is shown below. The result of this chunk is a dataset containing ---------------:

```{sql eval=FALSE}
select date(BLOCK_TIMESTAMP) as dates,
       recipient_label_type,
       recipient_label_subtype,
       recipient_label,
       count(distinct sender) as users
from terra.transfer_events
  where recipient_label_type in ('nft', 'dex', 'layer2', 'cex', 'defi', 'dapp')
group by dates,
       recipient_label_type,
       recipient_label_subtype,
       recipient_label
```

```{r include=FALSE}
data <- GET("https://api.flipsidecrypto.com/api/v2/queries/af747a83-b8c7-43db-9390-d43d759acea4/data/latest")
str(data)
data2 <- rawToChar(data$content)
data3 <- as_tibble(fromJSON(data2, flatten = TRUE))
data3$DATES <- as_date(data3$DATES)
to.remove <- ls()
to.remove <- c(to.remove[!grepl("data3", to.remove)], "to.remove")
rm(list=to.remove)
```


### Analysis
...............

```{r echo=FALSE, fig.width = 12}



```


..........

```{r echo=FALSE, fig.width = 12}



```

--------



### Conclusion

--


### References
https://flipsidecrypto.xyz/


Code used for this publication: https://github.com/manuelgirbal/flipside 

