---
title: "Avalanche Block and Transaction Performance
"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical layout: fill
    source_code: 
runtime: shiny
---
<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
library(flexdashboard)
library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)
library(shiny)
library(plotly)
library(DT)
library(rsconnect)
```

```{r data, include=FALSE}
options(scipen=999)

data_1 <- GET("https://node-api.flipsidecrypto.com/api/v2/queries/898b643f-c654-4e0c-8007-2a07aaadc4de/data/latest")
data_2 <- GET("https://node-api.flipsidecrypto.com/api/v2/queries/2bc0867d-d760-49d6-8c35-b5f4fd2c6dd4/data/latest")
data_3 <- GET("https://node-api.flipsidecrypto.com/api/v2/queries/bc15220d-d653-4025-8003-c98dd281f111/data/latest")

data2_1 <- rawToChar(data_1$content)
data2_2 <- rawToChar(data_2$content)
data2_3 <- rawToChar(data_3$content)

data3_1 <- as_tibble(fromJSON(data2_1, flatten = TRUE))
data3_2 <- as_tibble(fromJSON(data2_2, flatten = TRUE))
data3_3 <- as_tibble(fromJSON(data2_3, flatten = TRUE))

data3_1$DATE <- as_date(data3_1$DATE)
data3_3$DATE <- as_date(data3_3$DATE)

data3_1 <- data3_1 %>% 
  mutate(DATE_HOUR = as.POSIXct(paste(data3_1$DATE, data3_1$HOUR), format="%Y-%m-%d %H"))

data3_3 <- data3_3 %>% 
  mutate(DATE_HOUR = as.POSIXct(paste(data3_3$DATE, data3_3$HOUR), format="%Y-%m-%d %H"))

```




Column {data-width=300}
-----------------------------------------------------------------------
### Description

a
a

Data was queried from https://flipsidecrypto.xyz/


### A

```{r}
renderPlot({

})
```


Column {data-width=300}
-----------------------------------------------------------------------

### a

```{r}
renderPlot({

})
```



### A

```{r}
renderPlot({

})
```
